# Generated by Django 4.1.5 on 2023-01-02 23:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('form', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('revision_date', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField()),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('liste', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('revision_date', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField()),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('amac', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('kapsam', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tanimlar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('referanslar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('uygulama', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sorumluluk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('kontrol', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ekler', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('revision_date', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField()),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prosedur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('amac', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('kapsam', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tanimlar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('referanslar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('uygulama', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sorumluluk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('kontrol', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ekler', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('revision_date', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField()),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tablo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('tablo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('revision_date', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField()),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talimat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('talimat', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('revision_date', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField()),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
