# Generated by Django 4.1.5 on 2023-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_politika_kayit_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='form',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='form',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='prosedur',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='prosedur',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='prosedur',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='tablo',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='tablo',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='tablo',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='talimat',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='talimat',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='talimat',
            name='revision_number',
        ),
    ]
