# Generated by Django 4.1.5 on 2023-01-23 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_revision_remove_form_kayit_tarihi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revision',
        ),
        migrations.AddField(
            model_name='politika',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
