# Generated by Django 4.1.5 on 2023-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_form_upload_date_liste_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politika',
            name='revision_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
