# Generated by Django 4.1.5 on 2023-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_politika_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='revision_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liste',
            name='revision_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prosedur',
            name='revision_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablo',
            name='revision_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='talimat',
            name='revision_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
