# Generated by Django 4.1.5 on 2023-01-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_form_revision_date_liste_revision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablo',
            name='revision_date',
            field=models.DateTimeField(),
        ),
    ]
