# Generated by Django 4.1.5 on 2023-01-23 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_tablo_revision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablo',
            name='revision_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
