# Generated by Django 4.1.5 on 2023-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_tablo_revision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosedur',
            name='revision_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
