# Generated by Django 4.1.5 on 2023-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_alter_prosedur_revision_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='revision_date',
        ),
        migrations.AddField(
            model_name='form',
            name='rrevision_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='revision_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='politika',
            name='revision_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='revision_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='talimat',
            name='revision_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
