# Generated by Django 4.1.5 on 2023-01-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_remove_form_revision_date_form_rrevision_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='rrevision_date',
            new_name='revision_date',
        ),
    ]
