# Generated by Django 4.1.5 on 2023-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_form_revision_number_liste_revision_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politika',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prosedur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
